- job:
    name: brick-cinderclient-dsvm-functional-base
    abstract: true
    parent: devstack-tox-functional
    description: |
      Abstract job for defining devstack-based functional test jobs for
      python-brick-cinderclient-ext.  Jobs for particular python versions
      use this job as a parent, and control what verison of python is used
      by specifying a nodeset having the desired version of python as the
      system default.
    required-projects:
      - openstack/python-cinderclient
    timeout: 4200
    vars:
      devstack_localrc:
        LIBS_FROM_GIT: python-cinderclient
      devstack_services:
        # turn off ceilometer
        ceilometer-acentral: false
        ceilometer-acompute: false
        ceilometer-alarm-evaluator: false
        ceilometer-alarm-notifier: false
        ceilometer-anotification: false
        ceilometer-api: false
        ceilometer-collector: false
        # turn off swift
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        # turn off glance
        g-api: false
        g-reg: false
        # turn off nova
        n-api: false
        n-api-meta: false
        n-cauth: false
        n-cond: false
        n-cpu: false
        n-novnc: false
        n-obj: false
        n-sch: false
        placement-api: false
        # turn off misc
        horizon: false
        tempest: false
        c-bak: false
      # Hardcode brick-cinderclient path so the job can be run on other repo patches
      zuul_work_dir: src/opendev.org/openstack/python-brick-cinderclient-ext

- job:
    name: brick-cinderclient-dsvm-functional-py311
    parent: brick-cinderclient-dsvm-functional-base
    # Python 3.11 is the default on Debian Bookworm
    nodeset: devstack-single-node-debian-bookworm
    vars:
      bindep_profile: test py311
      python_version: '3.11'
      tox_envlist: functional-py311

- job:
    name: brick-cinderclient-dsvm-functional-py313
    parent: brick-cinderclient-dsvm-functional-base
    # Python 3.13 is the default on Debian Trixie
    nodeset: devstack-single-node-debian-trixie
    vars:
      bindep_profile: test py313
      python_version: '3.13'
      tox_envlist: functional-py313

- project:
    templates:
      - check-requirements
      - openstack-python3-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - brick-cinderclient-dsvm-functional-py311
        - brick-cinderclient-dsvm-functional-py313
    periodic-weekly:
      jobs:
        - openstack-tox-pep8:
            branches: master
        - openstack-tox-py311:
            branches: master
        - openstack-tox-py312:
            branches: master
        - openstack-tox-py313:
            branches: master
        - openstack-tox-py314:
            branches: master
        - openstack-tox-docs:
            branches: master
        - build-openstack-releasenotes:
            vars:
              sphinx_python: python3
            branches: master
        - python-cinderclient-functional-py311:
            branches: master
        - python-cinderclient-functional-py313:
            branches: master
    gate:
      jobs:
        - brick-cinderclient-dsvm-functional-py311
        - brick-cinderclient-dsvm-functional-py313
