- job:
    name: brick-cinderclient-dsvm-functional-base
    abstract: true
    parent: devstack-tox-functional
    description: |
      devstack-based functional tests for python-brick-cinderclient-ext
    required-projects:
      - openstack/python-cinderclient
    timeout: 4200
    vars:
      devstack_localrc:
        LIBS_FROM_GIT: python-cinderclient
      devstack_services:
        # turn off ceilometer
        ceilometer-acentral: false
        ceilometer-acompute: false
        ceilometer-alarm-evaluator: false
        ceilometer-alarm-notifier: false
        ceilometer-anotification: false
        ceilometer-api: false
        ceilometer-collector: false
        # turn off swift
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        # turn off glance
        g-api: false
        g-reg: false
        # turn off nova
        n-api: false
        n-api-meta: false
        n-cauth: false
        n-cond: false
        n-cpu: false
        n-novnc: false
        n-obj: false
        n-sch: false
        placement-api: false
        # turn off misc
        horizon: false
        tempest: false
        c-bak: false
      # Hardcode brick-cinderclient path so the job can be run on other repo patches
      zuul_work_dir: src/opendev.org/openstack/python-brick-cinderclient-ext

- job:
    name: brick-cinderclient-dsvm-functional-py39
    parent: brick-cinderclient-dsvm-functional-base
    nodeset: devstack-single-node-centos-9-stream
    vars:
      python_version: 3.9
      tox_envlist: functional-py39

- job:
    name: brick-cinderclient-dsvm-functional-py311
    parent: brick-cinderclient-dsvm-functional-base
    # use debian bookworm, where py3.11 is the default
    nodeset: devstack-single-node-debian-bookworm
    vars:
      python_version: 3.11
      tox_envlist: functional-py311

- project:
    templates:
      - check-requirements
      - openstack-python3-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - brick-cinderclient-dsvm-functional-py39
        - brick-cinderclient-dsvm-functional-py311
    gate:
      jobs:
        - brick-cinderclient-dsvm-functional-py39
        - brick-cinderclient-dsvm-functional-py311
